utils::globalVariables(c(
  "CPD_kg_month", "CPD_kg_month_YA", "CPD_kg_year", "CPD_kg_year_SD", "Compound",
"Concentration", "Concentration (ng/L)", "Concentrations", "DL (mg/day)", "Date",
"Flow" ,"Key" ,"MEC_Concentration", "MEC_SD","MEC_SPM_Concentration", "MEC_SPM_SD",
"MEC_effluent_Concentration", "MEC_effluent_SD", "MEC_influent_Concentration",
"MEC_influent_SD", "MEC_riverdown_Concentration", "MEC_riverdown_SD",
"MEC_riverup_Concentration", "MEC_riverup_SD", "Measure_Type", "PA", "PA_I", "PA_II",
"PA_effluent_I", "PA_effluent_II", "PA_influent_I", "PA_influent_II",
"PA_riverdown_I", "PA_riverdown_II", "PEC0II_effluent_Concentration",
"PEC0II_effluent_SD", "PEC0II_influent_Concentration", "PEC0II_influent_SD",
"PEC0II_riverdown_Concentration", "PEC0II_riverdown_SD",
"PEC0I_effluent_Concentration", "PEC0I_effluent_SD",
"PEC0I_influent_Concentration", "PEC0I_influent_SD",
"PEC0I_riverdown_Concentration", "PEC0I_riverdown_SD", "PEC_Concentration",
"PEC_SD", "PERIOD", "PNDL (mg/day/1000)", "PNDP_CPD_month", "PNDP_CPD_year", "PNDP_SM",
"PNDP_YA", "SD", "Total_Flow(m3)", "Total_PE", "Type", "WWinhab", "Year", "avg", "compare",
"date2", "dil_avg", "high", "key", "kg.month", "kgMonth", "kg_year", "kgmonth_SD", "kgmonth_SM",
"kgmonth_YA", "kgmonth_YD", "low", "mean_val", "month", "outcome", "period", "rm_eff",
"rm_eff_SD", "values"))
